"""Standard lattices as row-basis matrices (each row = a basis vector).
Normalized to det=1 (unit covolume) so results are scale-free.
Covering radius R and diam=2R validated against combigeo.voronoi_cell where feasible."""
import numpy as np, math

def _norm(B):
    B = np.asarray(B, float)
    n = B.shape[0]
    return B / abs(np.linalg.det(B))**(1.0/n)

def Z(n):
    return _norm(np.eye(n))

def A(n):
    # A_n in R^n via Gram: (n+1)x(n+1) minus, project. Use standard A_n basis rows e_i-e_{i+1} in R^{n+1}, then Gram-embed.
    M = np.zeros((n, n+1))
    for i in range(n):
        M[i, i] = 1; M[i, i+1] = -1
    G = M @ M.T
    B = np.linalg.cholesky(G)
    return _norm(B)

def Astar(n):
    # dual of A_n: basis = inverse-transpose of A_n basis (in the n-dim Gram embedding)
    M = np.zeros((n, n+1))
    for i in range(n):
        M[i, i] = 1; M[i, i+1] = -1
    G = M @ M.T
    Ginv = np.linalg.inv(G)
    B = np.linalg.cholesky(Ginv)
    return _norm(B)

def D(n):
    # D_n = {x in Z^n : sum even}. basis rows: e_i - e_{i+1} (i<n-1)?  use: {e1+e2}∪{e_{i+1}-e_i}
    B = np.zeros((n, n))
    B[0,0] = 1; B[0,1] = 1
    for i in range(1, n):
        B[i, i-1] = -1; B[i, i] = 1
    return _norm(B)

def Dstar(n):
    # D_n* generated by Z^n and (1/2,...,1/2): basis = e_1..e_{n-1}, (1/2,..,1/2)
    B = np.eye(n)
    B[n-1, :] = 0.5
    return _norm(B)

def E8():
    # E8 = D8 ∪ (D8 + (1/2)^8). Standard basis (rows):
    B = np.array([
        [2,0,0,0,0,0,0,0],
        [-1,1,0,0,0,0,0,0],
        [0,-1,1,0,0,0,0,0],
        [0,0,-1,1,0,0,0,0],
        [0,0,0,-1,1,0,0,0],
        [0,0,0,0,-1,1,0,0],
        [0,0,0,0,0,-1,1,0],
        [0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5],
    ], float)
    return _norm(B)

def E7():
    # E7 as sublattice of E8 (7-dim): take E8 Gram, restrict to first 7 simple roots
    # Simple roots of E7 (Bourbaki) in R^8, sum-zero style; use Gram directly.
    # Cartan/Gram of E7 root lattice:
    from numpy import array
    # E7 simple-root Gram (A-D-E): 7x7 with 2 on diag, -1 on E7 Dynkin edges
    # Dynkin E7: chain 1-3-4-5-6-7 with 2 attached to 4
    Gram = 2*np.eye(7)
    edges = [(0,2),(2,3),(3,4),(4,5),(5,6),(1,3)]  # 0-based, node2 (idx1) attaches to node4 (idx3)
    for a,b in edges:
        Gram[a,b] = Gram[b,a] = -1
    B = np.linalg.cholesky(Gram)
    return _norm(B)

def E7star():
    Gram = 2*np.eye(7)
    edges = [(0,2),(2,3),(3,4),(4,5),(5,6),(1,3)]
    for a,b in edges:
        Gram[a,b] = Gram[b,a] = -1
    Ginv = np.linalg.inv(Gram)
    B = np.linalg.cholesky(Ginv)
    return _norm(B)

def E6():
    Gram = 2*np.eye(6)
    edges = [(0,2),(2,3),(3,4),(4,5),(1,3)]  # E6 Dynkin
    for a,b in edges:
        Gram[a,b] = Gram[b,a] = -1
    B = np.linalg.cholesky(Gram)
    return _norm(B)

def E6star():
    Gram = 2*np.eye(6)
    edges = [(0,2),(2,3),(3,4),(4,5),(1,3)]
    for a,b in edges:
        Gram[a,b] = Gram[b,a] = -1
    Ginv = np.linalg.inv(Gram)
    B = np.linalg.cholesky(Ginv)
    return _norm(B)

CATALOG = {
    'A5*': lambda: Astar(5), 'D5': lambda: D(5), 'D5*': lambda: Dstar(5),
    'E6': E6, 'E6*': E6star, 'A6*': lambda: Astar(6), 'D6': lambda: D(6), 'D6*': lambda: Dstar(6),
    'E7': E7, 'E7*': E7star, 'A7*': lambda: Astar(7), 'D7': lambda: D(7), 'D7*': lambda: Dstar(7),
    'E8': E8, 'A8*': lambda: Astar(8), 'D8': lambda: D(8), 'D8*': lambda: Dstar(8),
    'A9*': lambda: Astar(9), 'D9': lambda: D(9), 'D9*': lambda: Dstar(9),
}

if __name__ == "__main__":
    import combigeo, time, sys
    names = sys.argv[1:] if len(sys.argv) > 1 else list(CATALOG)
    for name in names:
        B = CATALOG[name]()
        n = B.shape[0]
        lam1 = np.linalg.norm(combigeo.shortest_vector(B.tolist()))
        try:
            t = time.time()
            cell = combigeo.voronoi_cell(B.tolist())
            dt = time.time() - t
            nv = len(cell.vertices); nf = len(cell.facets)
            print(f"{name:5s} n={n} lam1={lam1:.4f} diam={cell.diameter:.4f} "
                  f"diam/lam1={cell.diameter/lam1:.4f} verts={nv} facets={nf} [{dt:.1f}s]", flush=True)
        except Exception as e:
            nrf = len(combigeo.relevant_facets(B.tolist()))
            print(f"{name:5s} n={n} lam1={lam1:.4f} voronoi_cell FAILED ({str(e)[:40]}); "
                  f"relevant_facets={nrf}", flush=True)
