"""Build a pool of g-invariant eigenvector forms (phi = eigenvector of A_g mod m,
kernel g-invariant), then SET-COVER: pick a few forms whose common kernel avoids
all forbidden vectors -> valid coloring, index = |image|. Reps suffice (forms are
<g,+-1>-invariant). Winner re-verified against the FULL forbidden set."""
import sys, numpy as np, itertools
sys.path.insert(0,"/Users/mac/Documents/_My_code/Chromatic/audit-data/hd-2026-07")
sys.path.insert(0,"/Users/mac/Documents/_My_code/Chromatic/audit-data")
from invariant_search import setup, orbit_reps

def modinv_ok(M, p):
    return np.linalg.matrix_rank(M) # unused placeholder

def nullspace_modp(A, p):
    """basis of right null space of A over GF(p) (A: rows x cols int)."""
    A = [[int(x) % p for x in row] for row in A]
    m = len(A); n = len(A[0]) if m else 0
    piv_col = []
    r = 0
    for c in range(n):
        # find pivot
        pr = None
        for i in range(r, m):
            if A[i][c] % p != 0: pr = i; break
        if pr is None: continue
        A[r], A[pr] = A[pr], A[r]
        inv = pow(A[r][c], p-2, p)
        A[r] = [(x*inv) % p for x in A[r]]
        for i in range(m):
            if i != r and A[i][c] % p != 0:
                f = A[i][c]
                A[i] = [(A[i][j] - f*A[r][j]) % p for j in range(n)]
        piv_col.append(c); r += 1
        if r == m: break
    pivset = set(piv_col)
    free = [c for c in range(n) if c not in pivset]
    basis = []
    for fc in free:
        v = [0]*n; v[fc] = 1
        for ri, c in enumerate(piv_col):
            v[c] = (-A[ri][fc]) % p
        basis.append(v)
    return basis   # list of null vectors mod p

def eigen_forms(Ag, p):
    """all (eigenvector a mod p, eigenvalue u): a with a·Ag ≡ u·a  (left eigvec)."""
    n = Ag.shape[0]; I = np.eye(n, dtype=np.int64)
    forms = []
    for u in range(1, p):                       # unit eigenvalues
        # left eigvec a: a(Ag - uI)=0  <=> (Ag - uI)^T a^T = 0 -> nullspace of (Ag^T-uI)
        M = (Ag.T - u*I)
        ns = nullspace_modp(M.tolist(), p)
        for a in ns:
            if any(x % p for x in a):
                forms.append((tuple(int(x)%p for x in a), p, u))
    return forms

def killed_mask(a, p, reps):
    """bool array: rep f with a·f ≡ 0 mod p (i.e. NOT separated by this form)."""
    R = np.array(reps, dtype=np.int64)
    return (R @ np.array(a, dtype=np.int64)) % p == 0

def image_index(forms_used, reps_dummy, n):
    """exact index = |image of phi=(a_j mod m_j)| via enumerating the subgroup
    generated by column vectors g_i=(a_j[i] mod m_j)."""
    from itertools import product as iproduct
    mods = [m for (_,m,_) in forms_used]
    A = [a for (a,_,_) in forms_used]
    gens = [tuple(A[j][i] % mods[j] for j in range(len(A))) for i in range(n)]
    seen = {tuple([0]*len(A))}; frontier=[tuple([0]*len(A))]
    while frontier:
        x = frontier.pop()
        for g in gens:
            y = tuple((x[j]+g[j]) % mods[j] for j in range(len(A)))
            if y not in seen: seen.add(y); frontier.append(y)
    return len(seen)

def greedy_cover(pool, nreps):
    """greedy set cover: repeatedly add the form separating the most still-killed
    reps. Returns list of forms whose common kernel avoids all reps (or None)."""
    killed = np.ones(nreps, dtype=bool)       # reps still killed by ALL chosen so far
    chosen = []
    used = set()
    while killed.any():
        best_i, best_gain = None, 0
        for i, f in enumerate(pool):
            if i in used: continue
            gain = int((killed & ~f['killed']).sum())   # reps this form would rescue
            if gain > best_gain: best_gain, best_i = gain, i
        if best_i is None or best_gain == 0:
            return None                        # cannot cover
        chosen.append(pool[best_i]); used.add(best_i)
        killed &= pool[best_i]['killed']
    return chosen

def search(n, moduli, index_cap=100000, greedy=True):
    S = setup(n); Ag, Fc = S['Ag'], S['Fc']
    reps = orbit_reps(Fc, Ag, n+1)
    pool = []
    for p in moduli:
        for (a,pp,u) in eigen_forms(Ag, p):
            km = killed_mask(a, pp, reps)
            pool.append(dict(a=a, m=pp, u=u, killed=km, nkill=int(km.sum())))
    print(f"n={n}: |F|={len(Fc)} reps={len(reps)}  pool={len(pool)} forms over {moduli}", flush=True)
    reps_arr = np.array(reps, dtype=np.int64)
    chosen = greedy_cover(pool, len(reps))
    if chosen is None:
        print("  greedy: NO covering exists in this pool", flush=True); return None
    idx = image_index([(f['a'],f['m'],f['u']) for f in chosen], reps_arr, n)
    allk = ((Fc @ np.array(chosen[0]['a'])) % chosen[0]['m'] == 0)
    for f in chosen[1:]: allk &= ((Fc @ np.array(f['a'])) % f['m'] == 0)
    ok = not allk.any()
    print(f"  greedy covering: {len(chosen)} forms {[(f['m'],f['u']) for f in chosen]}  "
          f"index={idx}  full-F valid={ok}", flush=True)
    return idx, chosen, ok

def min_index_search(n, moduli, cap, maxr=4):
    """exhaustively find the MIN-index invariant covering (index < cap)."""
    S = setup(n); Ag, Fc = S['Ag'], S['Fc']
    reps = orbit_reps(Fc, Ag, n+1); reps_arr = np.array(reps, dtype=np.int64)
    pool = []
    for p in moduli:
        for (a,pp,u) in eigen_forms(Ag, p):
            km = killed_mask(a, pp, reps)
            pool.append(dict(a=a, m=pp, u=u, killed=km))
    print(f"n={n}: |F|={len(Fc)} reps={len(reps)}  pool={len(pool)} forms", flush=True)
    best = None
    for r in range(2, maxr+1):
        cnt = 0
        for combo in itertools.combinations(range(len(pool)), r):
            fs = [pool[i] for i in combo]
            # prune by modulus product (lower bound on index)
            from math import prod
            if prod(f['m'] for f in fs) >= (best[0] if best else cap): continue
            allk = fs[0]['killed'].copy()
            for f in fs[1:]: allk &= f['killed']
            if allk.any(): continue
            idx = image_index([(f['a'],f['m'],f['u']) for f in fs], reps_arr, n)
            if idx < (best[0] if best else cap):
                # full-F verify
                fk = ((Fc @ np.array(fs[0]['a'])) % fs[0]['m'] == 0)
                for f in fs[1:]: fk &= ((Fc @ np.array(f['a'])) % f['m'] == 0)
                if not fk.any():
                    best = (idx, [(f['m'],f['u']) for f in fs], [f['a'] for f in fs])
                    print(f"  NEW min index={idx} forms={best[1]}", flush=True)
            cnt += 1
        print(f"  r={r}: checked {cnt} combos, best={best[0] if best else None}", flush=True)
    if best: print(f"=== MIN-INDEX invariant coloring: chi(R^{n}) <= {best[0]}  forms={best[1]} ===", flush=True)
    else: print(f"  no covering < {cap}", flush=True)
    return best

if __name__ == "__main__":
    n = int(sys.argv[1]); moduli = eval(sys.argv[2])
    mode = sys.argv[3] if len(sys.argv)>3 else 'greedy'
    if mode == 'min':
        cap = int(sys.argv[4]) if len(sys.argv)>4 else 1372
        maxr = int(sys.argv[5]) if len(sys.argv)>5 else 4
        min_index_search(n, moduli, cap, maxr)
    else:
        search(n, moduli)
