"""Fast covering-radius oracle for the permutohedral secondary cone.

The Voronoi cell of ``A_n^*`` is the permutohedron.  Write its physical
superbase as ``g_0, ..., g_n`` with sum zero.  Its facet vectors are the
nonempty proper subset sums of the superbase.  A Voronoi vertex is indexed by
a permutation: the active facet vectors are the successive prefix sums.

For a permutation ending in ``j``, the other ``n`` superbase vectors form one
fixed basis (up to row permutation).  If ``s_k`` is the prefix before the next
vector ``g_i``, its circumcenter ``x`` satisfies

    <g_i, x> = <s_k, g_i> + |g_i|^2 / 2.

Thus only ``n+1`` Gram inverses are needed.  All ``(n+1)!`` vertices can then
be evaluated in vectorized batches.  This avoids generic halfspace vertex
enumeration, which is prohibitive for the 3,628,800 vertices of ``A_9^*``.

The oracle is exact up to floating-point arithmetic as long as the form stays
inside the same Delone secondary cone.  Outside that cone it is a search
surrogate; final lattice-coloring candidates must still be checked by the
complete generic oracle.
"""

from __future__ import annotations

import itertools
import math
from functools import lru_cache
from typing import Sequence

import numpy as np


def superbase_from_astar_basis(basis: Sequence[Sequence[float]]) -> np.ndarray:
    """Return the ``n+1`` physical superbase vectors for an A-star row basis."""
    basis_array = np.asarray(basis, dtype=np.float64)
    n = len(basis_array)
    if basis_array.shape != (n, n):
        raise ValueError("basis must be square")
    superbase = np.empty((n + 1, n), dtype=np.float64)
    superbase[0] = basis_array[0]
    if n > 1:
        superbase[1:n] = basis_array[1:] - basis_array[:-1]
    superbase[n] = -basis_array[-1]
    if not np.allclose(superbase.sum(axis=0), 0.0, atol=2e-12):
        raise AssertionError("constructed superbase does not sum to zero")
    return superbase


def permutohedral_facet_coordinates(n: int) -> np.ndarray:
    """All oriented nonzero proper-subset facet vectors in lattice coordinates."""
    if n < 1:
        raise ValueError("dimension must be positive")
    masks = np.arange(1, (1 << (n + 1)) - 1, dtype=np.uint64)
    bits = (
        (masks[:, None] >> np.arange(n + 1, dtype=np.uint64)) & 1
    ).astype(np.int8)
    # A projected binary vector u has fundamental-weight coordinates
    # (u_0-u_1, ..., u_{n-1}-u_n).
    return (bits[:, :-1] - bits[:, 1:]).astype(np.int64)


def permutohedral_facets(
    basis: Sequence[Sequence[float]],
) -> list[tuple[list[float], float]]:
    """Facet halfspaces generated by all proper superbase subset sums."""
    basis_array = np.asarray(basis, dtype=np.float64)
    coordinates = permutohedral_facet_coordinates(len(basis_array))
    vectors = coordinates @ basis_array
    norms = np.linalg.norm(vectors, axis=1)
    return [
        (vector.tolist(), float(norm / 2.0))
        for vector, norm in zip(vectors, norms)
    ]


def _squared_radii_for_orders(
    superbase: np.ndarray,
    orders: np.ndarray,
) -> np.ndarray:
    """Circumradius squared for explicit full superbase permutations."""
    superbase = np.asarray(superbase, dtype=np.float64)
    n = superbase.shape[1]
    orders = np.asarray(orders, dtype=np.int64)
    if orders.ndim != 2 or orders.shape[1] != n + 1:
        raise ValueError(f"orders must have shape (m, {n + 1})")
    if len(orders) == 0:
        raise ValueError("orders must be nonempty")
    gram = superbase @ superbase.T
    all_labels = np.arange(n + 1, dtype=np.int64)
    squared = np.empty(len(orders), dtype=np.float64)

    for omitted in range(n + 1):
        selected = np.flatnonzero(orders[:, -1] == omitted)
        if not len(selected):
            continue
        labels = all_labels[all_labels != omitted]
        label_positions = np.full(n + 1, -1, dtype=np.int64)
        label_positions[labels] = np.arange(n)
        inverse_gram = np.linalg.inv(gram[np.ix_(labels, labels)])
        order = orders[selected, :-1]
        rhs_by_position = np.empty((len(order), n), dtype=np.float64)
        for position in range(n):
            current = order[:, position]
            rhs = 0.5 * gram[current, current]
            if position:
                previous = order[:, :position]
                rhs = rhs + gram[previous, current[:, None]].sum(axis=1)
            rhs_by_position[:, position] = rhs
        rhs = np.empty_like(rhs_by_position)
        np.put_along_axis(
            rhs,
            label_positions[order],
            rhs_by_position,
            axis=1,
        )
        squared[selected] = np.einsum(
            "bi,ij,bj->b",
            rhs,
            inverse_gram,
            rhs,
            optimize=True,
        )
    if not np.all(np.isfinite(squared)):
        raise RuntimeError("non-finite circumradius in explicit order archive")
    return squared


def radii_for_orders(
    basis: Sequence[Sequence[float]],
    orders: np.ndarray,
) -> np.ndarray:
    """Circumradii for an explicit archive of Delone permutations."""
    superbase = superbase_from_astar_basis(basis)
    return np.sqrt(_squared_radii_for_orders(superbase, orders))


def covering_radius_for_orders(
    basis: Sequence[Sequence[float]],
    orders: np.ndarray,
    *,
    with_witness: bool = False,
) -> tuple[float, dict | None]:
    """Maximum radius over an explicit permutation archive."""
    radii = radii_for_orders(basis, orders)
    index = int(np.argmax(radii))
    witness = None
    if with_witness:
        witness = {
            "permutation": np.asarray(orders[index], dtype=int).tolist(),
            "radius_squared": float(radii[index] ** 2),
        }
    return float(radii[index]), witness


@lru_cache(maxsize=None)
def permutation_table(n: int) -> np.ndarray:
    """All permutations of ``range(n)`` as a compact read-only array."""
    if n < 1:
        raise ValueError("dimension must be positive")
    flat = np.fromiter(
        itertools.chain.from_iterable(itertools.permutations(range(n))),
        dtype=np.uint8 if n <= 255 else np.uint16,
        count=math.factorial(n) * n,
    )
    table = flat.reshape(-1, n)
    table.flags.writeable = False
    return table


def covering_radius(
    basis: Sequence[Sequence[float]],
    *,
    batch_size: int = 65_536,
    with_witness: bool = False,
) -> tuple[float, int, dict | None]:
    """Maximum circumradius over every permutohedral Delone simplex."""
    basis_array = np.asarray(basis, dtype=np.float64)
    n = len(basis_array)
    if basis_array.shape != (n, n):
        raise ValueError("basis must be square")
    if batch_size < 1:
        raise ValueError("batch size must be positive")

    superbase = superbase_from_astar_basis(basis_array)
    gram = superbase @ superbase.T
    permutations = permutation_table(n)
    maximum_squared = -np.inf
    maximum_order: np.ndarray | None = None
    maximum_omitted = -1
    maximum_rhs: np.ndarray | None = None

    all_labels = np.arange(n + 1, dtype=np.int64)
    for omitted in range(n + 1):
        labels = all_labels[all_labels != omitted]
        label_positions = np.full(n + 1, -1, dtype=np.int64)
        label_positions[labels] = np.arange(n)
        inverse_gram = np.linalg.inv(gram[np.ix_(labels, labels)])

        for start in range(0, len(permutations), batch_size):
            order = labels[permutations[start : start + batch_size]]
            count = len(order)
            rhs_by_position = np.empty((count, n), dtype=np.float64)
            for position in range(n):
                current = order[:, position]
                rhs = 0.5 * gram[current, current]
                if position:
                    previous = order[:, :position]
                    rhs = rhs + gram[previous, current[:, None]].sum(axis=1)
                rhs_by_position[:, position] = rhs

            rhs = np.empty_like(rhs_by_position)
            np.put_along_axis(
                rhs,
                label_positions[order],
                rhs_by_position,
                axis=1,
            )
            squared = np.einsum(
                "bi,ij,bj->b",
                rhs,
                inverse_gram,
                rhs,
                optimize=True,
            )
            local_index = int(np.argmax(squared))
            local_squared = float(squared[local_index])
            if local_squared > maximum_squared:
                maximum_squared = local_squared
                maximum_order = order[local_index].copy()
                maximum_omitted = omitted
                maximum_rhs = rhs[local_index].copy()

    if not np.isfinite(maximum_squared) or maximum_order is None:
        raise RuntimeError("failed to enumerate a finite circumradius")
    witness = None
    if with_witness:
        labels = all_labels[all_labels != maximum_omitted]
        physical_basis = superbase[labels]
        assert maximum_rhs is not None
        center = np.linalg.solve(physical_basis, maximum_rhs)
        witness = {
            "permutation": maximum_order.astype(int).tolist()
            + [int(maximum_omitted)],
            "center": center.tolist(),
            "radius_squared": maximum_squared,
        }
    return float(np.sqrt(maximum_squared)), math.factorial(n + 1), witness
